### ISSUE TITLE
It cannot work with Spring Data JPA.

### ISSUE THREAD

**Issue by ldwqh0** [TongchengOpenSource/smart-doc-gradle-plugin#5]
After migrating my project to Gradle and using the plugin to build the documentation, I kept encountering errors without being able to identify the cause. Therefore, I started over with building the project from scratch, adding dependencies bit by bit, and that's when I discovered the issue. Below are the configurations of my project.
settings.gradle
```
rootProject.name = "test-smart-project"
```

build.gradle
```
plugins {
    id 'java'
    id("org.springframework.boot") version "2.5.3"
    id("io.spring.dependency-management") version "1.0.11.RELEASE"
    id("com.github.shalousun.smart-doc") version "2.3.4"
}
group = "com.xzcode"
version = "0.1.0-SNAPSHOT"
repositories {
    mavenLocal()
    mavenCentral()
}
smartdoc {
    configFile = file("src/main/resources/smart-doc.json")
}
java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-web"
//    implementation "org.springframework.boot:spring-boot-starter-data-jpa"
    implementation 'com.h2database:h2:2.0.202'

    testImplementation "org.junit.jupiter:junit-jupiter-api"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine"
}
```

There's no other code; it's just the addition of a class.
src/main/java/com/mrwang/mp/Testapplication.java
```
@SpringBootApplication
@RestController
@RequestMapping("test")
public class TestApplication {
    public static void main(String[] args) {
        SpringApplication.run(TestApplication.class, args);
    }

    /**
     * A simple test
     */
    @GetMapping
    public String test() {
        return "wo de";
    }
}
```

Once I added `// implementation "org.springframework.boot:spring-boot-starter-data-jpa"` to the project, an error would occur during the documentation build, with the prompt Error: could not match input.
However, if I removed `implementation "org.springframework.boot:spring-boot-starter-data-jpa"` from the project, everything went smoothly.

**Comment by shalousun** [comment]
@ldwqh0 https://smart-doc-group.github.io/#/zh-cn/QA?id=could-not-match-input%ef%bc%9f
