### ISSUE TITLE
Has the latest version not been released to the Gradle plugin center? Why is it only compatible with 2.5.2?

### ISSUE THREAD

**Issue by jkelink** [TongchengOpenSource/smart-doc-gradle-plugin#7]
## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
2.
3.
4.

## Your Environment(您的使用环境)

* smart-doc version:
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin):
* build tool version(maven or gradle):

**Comment by jkelink** [comment]
https://repo.gradle.org/ui/native/jcenter/com/github/shalousun/smart-doc/2.6.2/smart-doc-2.6.2.pom

```
{
  "errors": [
    {
      "status": 404,
      "message": "Item jcenter-cache:com/github/shalousun/smart-doc/2.6.2/smart-doc-2.6.2.pom does not exist"
    }
  ]
}
```

**Comment by shalousun** [comment]
@jinkun2014 Since 2.5.2, the Gradle plugin is no longer published to the Maven central repository and is only released to https://plugins.gradle.org/.
