### ISSUE TITLE
[Unable to use] It seems that custom source sets are not supported, and interface documentation cannot be generated.

### ISSUE THREAD

**Issue by syrm-ll** [TongchengOpenSource/smart-doc-gradle-plugin#9]
My project structure is somewhat unique, with the following configurations:
```kotlin
subprojects {
    apply(plugin = "java")

    java {
        sourceSets {
            main {
                java { setSrcDirs(listOf("java")) }
                resources { setSrcDirs(listOf("resources")) }
            }
            test {
                java { setSrcDirs(listOf("test")) }
                resources { setSrcDirs(listOf("testResources")) }
            }
        }
    }
}

```
The project structure is roughly like this:
![image](https://user-images.githubusercontent.com/40515646/220918908-324d6729-5f15-47bf-8e17-fc504d136432.png)

The relevant configurations for smart-doc:
```kotlin
plugins {
    java
    id("org.springframework.boot") version "3.0.2"
    id("io.spring.dependency-management") version "1.1.0"
    @Suppress("SpellCheckingInspection")
    id("com.github.shalousun.smart-doc") version "2.2.3"
}

smartdoc {
    configFile = file("resources/smart-doc.json")
}
```
The smart-doc.json is just copied from the official website; there are no special configurations.

After running the command to generate the documentation, onlyAfter running the command to generate the documentation, only read, and not a single only the project information could be read, and not a single interface was detected.
Here, I'll use `smartDocOpenApi` as an example:

```log
21:24:11: 正在执行 'smartDocOpenApi'…

> Task :yun-baidu:baidu-image-process:compileJava UP-TO-DATE
> Task :application:app-image-process-server:compileJava UP-TO-DATE

> Task :application:app-image-process-server:smartDocOpenApi
Smart-doc Starting Create API Documentation.
The loaded local code path is C:\code\开放平台接入\application\app-image-process-server\src\main\java
The loaded local code path is C:\code\开放平台接入\yun-baidu\baidu-image-process\src/main/java
syntax error @[32,18] in jar:file:/C:/env/data/gradle/caches/modules-2/files-2.1/pub.syrm.tool/core/1.0-SNAPSHOT/c04be76fdd9e5f799c5014182822b11f50d8cff4/core-1.0-SNAPSHOT-sources.jar!/pub/syrm/tool/model/Tuple.java
syntax error @[37,8] in jar:file:/C:/env/data/gradle/caches/modules-2/files-2.1/org.springframework/spring-core/6.0.4/c82cc3af52dbea3aa7841ca8cbe0959bc395e08e/spring-core-6.0.4-sources.jar!/org/springframework/core/io/support/PropertySourceDescriptor.java
syntax error @[349,27] in jar:file:/C:/env/data/gradle/caches/modules-2/files-2.1/org.springframework/spring-core/6.0.4/c82cc3af52dbea3aa7841ca8cbe0959bc395e08e/spring-core-6.0.4-sources.jar!/org/springframework/util/ConcurrentLruCache.java
API Documentation output to C:\code\开放平台接入\application\app-image-process-server/resources/static/doc

BUILD SUCCESSFUL in 2s
3 actionable tasks: 1 executed, 2 up-to-date
21:24:13: 执行完成 'smartDocOpenApi'。

```
生成的文件: 
![image](https://user-images.githubusercontent.com/40515646/220919715-509590f4-defe-48f4-ab46-95280acefe0f.png)

# Problem
The problem is uncertain at the moment, but I suspect that you've hardcoded the `src/main/java` path without taking the configuration from `sourceSets`.
If it's confirmed that there's no issue with supporting `sourceSets`, I'll create a minimal reproduction case.

**Comment by shalousun** [comment]
@syrm-ll 可以看下gradle插件的源码，修改题个pr支持，之前插件是按照java项目默认结构肯定就写死了，自定义的之前都没遇到过

**Comment by syrm-ll** [comment]
> @syrm-ll 可以看下gradle插件的源码，修改题个pr支持，之前插件是按照java项目默认结构肯定就写死了，自定义的之前都没遇到过

QAQ ... 我 gradle 还没用熟悉呢, 以后吧 如果我能研究明白

**Comment by syrm-ll** [comment]
@shalousun  <https://github.com/smart-doc-group/smart-doc-gradle-plugin/pull/10>
